version: '3'
services:
  frontend:
    build:
      context: ./make-sense
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./AI_Backend/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # Add any other configurations for your backend service here
